### ISSUE TITLE
Unbound value serialize_list

### ISSUE THREAD

**Issue by shubhamkumar13** [leostera/serde.ml#6]
```ocaml
 type exp =
  | Int of int
  | Unit of unit
  | Prim of op * exp list
[@@deriving serializer, deserializer]
```
results in Unbound value `serialize_list`
```bash
❯ dune exec bin/main.exe
File "bin/main.ml", lines 105-109, characters 0-37:
105 | type exp =
106 |   | Int of int
107 |   | Unit of unit
108 |   | Prim of op * exp list
109 | [@@deriving serializer, deserializer]
Error: Unbound value serialize_list
```

Is there a way to implement `serialize_list` manually?
I understand that this repo is currently a wip but I wanted to experiment with it

Thanks!

**Comment by leostera** [comment]
Thanks for creating the issue! 🙏

We probably want to provide a default serializer for the list type. In PR #5 we are adding this for the `option` type, and it should be similar but easier. Similar because we need to extend serde_derive to treat the `list` type specially, but easier because we already have support for deserializing sequences.

I can have a look over the weekend :)

**Comment by leostera** [comment]
The latest rewrite in #8 fixes this! And we have tests for both lists and arrays.
